# docker-compose.yml
version: '3.8'

services:
  node1:
    build: .
    command: python blockchain_node.py config/node1_config.json # FIXED: Pointing to blockchain_node.py
    ports:
      - "5001:5001" # Host_port:Container_port
    networks:
      - consortium_network
    volumes:
      - ./initial_policies.json:/app/initial_policies.json
      - ./config:/app/config

  node2:
    build: .
    command: python blockchain_node.py config/node2_config.json # FIXED: Pointing to blockchain_node.py
    ports:
      - "5002:5002"
    networks:
      - consortium_network
    depends_on:
      - node1
    volumes:
      - ./initial_policies.json:/app/initial_policies.json
      - ./config:/app/config

  node3:
    build: .
    command: python blockchain_node.py config/node3_config.json # FIXED: Pointing to blockchain_node.py
    ports:
      - "5003:5003"
    networks:
      - consortium_network
    depends_on:
      - node1
      - node2
    volumes:
      - ./initial_policies.json:/app/initial_policies.json
      - ./config:/app/config

  node4:
    build: .
    command: python blockchain_node.py config/node4_config.json # FIXED: Pointing to blockchain_node.py
    ports:
      - "5004:5004"
    networks:
      - consortium_network
    depends_on:
      - node1
      - node2
      - node3
    volumes:
      - ./initial_policies.json:/app/initial_policies.json
      - ./config:/app/config

networks:
  consortium_network:
    driver: bridge
